/**
 * Stable leg kind ids — must match `PlayscriptV2Grading.sol` (`legHitByKind`).
 * Slot index 0–14 in a market maps to `legKinds[slot]`; bitmask bit `i` grades `legKinds[i]`.
 */

export const V2_SOCCER_LEG_KINDS = {
  HOME_WIN: 1,
  AWAY_WIN: 2,
  DRAW: 3,
  OVER_25: 4,
  UNDER_15: 5,
  /** Pairs with OVER_25 (total goals ≤ 2). */
  UNDER_25: 36,
  BTTS: 6,
  HOME_CS: 7,
  AWAY_CS: 8,
  HOME_WIN_2PLUS: 9,
  AWAY_WIN_2PLUS: 10,
  FH_ANY_GOAL: 11,
  BOTH_UNDER_3: 12,
  HOME_LEAD_HT: 13,
  AWAY_LEAD_HT: 14,
  DRAW_HT: 15,
  MATCH_YELLOW_2PLUS: 16,
  HOME_HT_OVER_05: 20,
  AWAY_HT_OVER_05: 21,
  HOME_RED_CARD: 23,
  AWAY_RED_CARD: 24,
  HT_OVER_15: 25,
  HT_UNDER_05: 26,
  HOME_HT_CS: 27,
  AWAY_HT_CS: 28,
  HOME_SCORES_2PLUS: 29,
  AWAY_SCORES_2PLUS: 30,
  HOME_YELLOW_1PLUS: 31,
  AWAY_YELLOW_1PLUS: 32,
  HOME_YELLOW_2PLUS: 33,
  AWAY_YELLOW_2PLUS: 34,
  BOTH_TEAMS_YELLOW: 35,
  /** 2nd-half combined goals ≥ 2 (derived from FT − HT). */
  SH_OVER_15: 37,
  /** Each team scores ≥1 in 2nd half (derived). */
  SH_BTTS: 39,
} as const;

export const V2_BASKETBALL_LEG_KINDS = {
  HOME_WIN: 41,
  AWAY_WIN: 42,
  OVER_225: 43,
  UNDER_200: 44,
  BOTH_100_PLUS: 45,
  BOTH_UNDER_120: 46,
  HOME_WIN_10PLUS: 47,
  AWAY_WIN_10PLUS: 48,
  FIRST_HALF_OVER_115: 49,
  TOTAL_230_PLUS: 50,
  MARGIN_20_PLUS: 51,
  BOTH_UNDER_110: 52,
  Q1_COMBINED_OVER_55: 53,
  HOME_Q1_OVER_28: 54,
  AWAY_Q1_OVER_28: 55,
} as const;

export const V2_NFL_LEG_KINDS = {
  HOME_WIN: 61,
  AWAY_WIN: 62,
  OVER_45: 63,
  UNDER_38: 64,
  BOTH_17_PLUS: 65,
  HOME_ALLOWS_10: 66,
  AWAY_ALLOWS_10: 67,
  MARGIN_10_PLUS: 68,
  FIRST_HALF_OVER_23: 69,
  BOTH_24_PLUS: 70,
  TOTAL_55_PLUS: 71,
  EITHER_SHUTOUT: 72,
  Q1_COMBINED_OVER_14: 73,
  HOME_20_PLUS: 74,
  AWAY_20_PLUS: 75,
} as const;

export const V2_MLB_LEG_KINDS = {
  HOME_WIN: 81,
  AWAY_WIN: 82,
  OVER_9_5: 83,
  UNDER_7_5: 84,
  BOTH_4_PLUS: 85,
  HOME_5_PLUS: 86,
  AWAY_5_PLUS: 87,
  TOTAL_10_PLUS: 88,
  MARGIN_3_PLUS: 89,
  BOTH_SCORE: 90,
  EITHER_SHUTOUT: 91,
  BOTH_UNDER_7: 92,
  OVER_8_5: 93,
  HOME_3_PLUS: 94,
  AWAY_3_PLUS: 95,
} as const;

/** Fixed 15-leg soccer market — all settle from ESPN scoreboard + summary (no extra fetches). */
export const V2_SOCCER_MARKET_LEG_KINDS: readonly number[] = [
  V2_SOCCER_LEG_KINDS.HOME_WIN,
  V2_SOCCER_LEG_KINDS.AWAY_WIN,
  V2_SOCCER_LEG_KINDS.DRAW,
  V2_SOCCER_LEG_KINDS.HOME_LEAD_HT,
  V2_SOCCER_LEG_KINDS.AWAY_LEAD_HT,
  V2_SOCCER_LEG_KINDS.DRAW_HT,
  V2_SOCCER_LEG_KINDS.OVER_25,
  V2_SOCCER_LEG_KINDS.UNDER_25,
  V2_SOCCER_LEG_KINDS.HT_OVER_15,
  V2_SOCCER_LEG_KINDS.HT_UNDER_05,
  V2_SOCCER_LEG_KINDS.BTTS,
  V2_SOCCER_LEG_KINDS.HOME_CS,
  V2_SOCCER_LEG_KINDS.AWAY_CS,
  V2_SOCCER_LEG_KINDS.SH_OVER_15,
  V2_SOCCER_LEG_KINDS.SH_BTTS,
];

/** Fixed 15-leg basketball market. */
export const V2_BASKETBALL_MARKET_LEG_KINDS: readonly number[] = [
  V2_BASKETBALL_LEG_KINDS.HOME_WIN,
  V2_BASKETBALL_LEG_KINDS.AWAY_WIN,
  V2_BASKETBALL_LEG_KINDS.OVER_225,
  V2_BASKETBALL_LEG_KINDS.UNDER_200,
  V2_BASKETBALL_LEG_KINDS.HOME_WIN_10PLUS,
  V2_BASKETBALL_LEG_KINDS.AWAY_WIN_10PLUS,
  V2_BASKETBALL_LEG_KINDS.BOTH_100_PLUS,
  V2_BASKETBALL_LEG_KINDS.BOTH_UNDER_120,
  V2_BASKETBALL_LEG_KINDS.FIRST_HALF_OVER_115,
  V2_BASKETBALL_LEG_KINDS.Q1_COMBINED_OVER_55,
  V2_BASKETBALL_LEG_KINDS.HOME_Q1_OVER_28,
  V2_BASKETBALL_LEG_KINDS.AWAY_Q1_OVER_28,
  V2_BASKETBALL_LEG_KINDS.TOTAL_230_PLUS,
  V2_BASKETBALL_LEG_KINDS.MARGIN_20_PLUS,
  V2_BASKETBALL_LEG_KINDS.BOTH_UNDER_110,
];

/** Fixed 15-leg NFL market. */
export const V2_NFL_MARKET_LEG_KINDS: readonly number[] = [
  V2_NFL_LEG_KINDS.HOME_WIN,
  V2_NFL_LEG_KINDS.AWAY_WIN,
  V2_NFL_LEG_KINDS.OVER_45,
  V2_NFL_LEG_KINDS.UNDER_38,
  V2_NFL_LEG_KINDS.HOME_ALLOWS_10,
  V2_NFL_LEG_KINDS.AWAY_ALLOWS_10,
  V2_NFL_LEG_KINDS.BOTH_17_PLUS,
  V2_NFL_LEG_KINDS.BOTH_24_PLUS,
  V2_NFL_LEG_KINDS.FIRST_HALF_OVER_23,
  V2_NFL_LEG_KINDS.Q1_COMBINED_OVER_14,
  V2_NFL_LEG_KINDS.MARGIN_10_PLUS,
  V2_NFL_LEG_KINDS.EITHER_SHUTOUT,
  V2_NFL_LEG_KINDS.TOTAL_55_PLUS,
  V2_NFL_LEG_KINDS.HOME_20_PLUS,
  V2_NFL_LEG_KINDS.AWAY_20_PLUS,
];

/** Fixed 15-leg MLB market (final score only onchain). */
export const V2_MLB_MARKET_LEG_KINDS: readonly number[] = [
  V2_MLB_LEG_KINDS.HOME_WIN,
  V2_MLB_LEG_KINDS.AWAY_WIN,
  V2_MLB_LEG_KINDS.OVER_9_5,
  V2_MLB_LEG_KINDS.UNDER_7_5,
  V2_MLB_LEG_KINDS.HOME_5_PLUS,
  V2_MLB_LEG_KINDS.AWAY_5_PLUS,
  V2_MLB_LEG_KINDS.BOTH_4_PLUS,
  V2_MLB_LEG_KINDS.BOTH_UNDER_7,
  V2_MLB_LEG_KINDS.BOTH_SCORE,
  V2_MLB_LEG_KINDS.EITHER_SHUTOUT,
  V2_MLB_LEG_KINDS.MARGIN_3_PLUS,
  V2_MLB_LEG_KINDS.TOTAL_10_PLUS,
  V2_MLB_LEG_KINDS.OVER_8_5,
  V2_MLB_LEG_KINDS.HOME_3_PLUS,
  V2_MLB_LEG_KINDS.AWAY_3_PLUS,
];
