/** Narrow ABI for `PlayscriptKernel` (v2) — keep aligned with `contracts/v2/PlayscriptKernel.sol`. */

const matchSelComponents = [
  { name: "homeScore", type: "string" },
  { name: "awayScore", type: "string" },
  { name: "htHome", type: "string" },
  { name: "htAway", type: "string" },
  { name: "yellowHome", type: "string" },
  { name: "yellowAway", type: "string" },
  { name: "redHome", type: "string" },
  { name: "redAway", type: "string" },
  { name: "homeQ1", type: "string" },
  { name: "homeQ2", type: "string" },
  { name: "awayQ1", type: "string" },
  { name: "awayQ2", type: "string" },
] as const;

const matchTupleComponents = [
  { name: "sport", type: "uint8" },
  { name: "kickoff", type: "uint64" },
  { name: "finalizeDelaySec", type: "uint32" },
  { name: "url", type: "string" },
  { name: "scoreboardUrl", type: "string" },
  { name: "summaryUrl", type: "string" },
  { name: "sel", type: "tuple", components: [...matchSelComponents] },
  { name: "state", type: "uint8" },
  { name: "legKinds", type: "uint8[12]" },
  { name: "legWeights", type: "uint8[12]" },
  { name: "exists", type: "bool" },
  { name: "settled", type: "bool" },
  { name: "settleInProgress", type: "bool" },
  { name: "fetchMask", type: "uint16" },
  { name: "finalHome", type: "uint256" },
  { name: "finalAway", type: "uint256" },
  { name: "htHome", type: "uint256" },
  { name: "htAway", type: "uint256" },
  { name: "yellowHome", type: "uint256" },
  { name: "yellowAway", type: "uint256" },
  { name: "redHome", type: "uint256" },
  { name: "redAway", type: "uint256" },
  { name: "homeQ1", type: "uint256" },
  { name: "homeQ2", type: "uint256" },
  { name: "awayQ1", type: "uint256" },
  { name: "awayQ2", type: "uint256" },
  { name: "resolvedLegsBitmask", type: "uint16" },
  { name: "matchLiabilityCap", type: "uint256" },
  { name: "matchLiability", type: "uint256" },
] as const;

export const playscriptKernelReadAbi = [
  {
    type: "function",
    name: "nextMatchId",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "matches",
    stateMutability: "view",
    inputs: [{ name: "matchId", type: "uint256" }],
    outputs: [{ type: "tuple", components: [...matchTupleComponents] }],
  },
  {
    type: "function",
    name: "vault",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "address" }],
  },
  {
    type: "function",
    name: "lockRoom",
    stateMutability: "view",
    inputs: [{ name: "matchId", type: "uint256" }],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "getPayoutRate",
    stateMutability: "pure",
    inputs: [{ name: "difficultyScore", type: "uint256" }],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "payoutRateForMask",
    stateMutability: "view",
    inputs: [
      { name: "matchId", type: "uint256" },
      { name: "legMask12", type: "uint16" },
    ],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "isWinningMask",
    stateMutability: "view",
    inputs: [
      { name: "matchId", type: "uint256" },
      { name: "legMask12", type: "uint16" },
    ],
    outputs: [{ type: "bool" }],
  },
  {
    type: "function",
    name: "difficultyScore",
    stateMutability: "view",
    inputs: [
      { name: "matchId", type: "uint256" },
      { name: "legMask12", type: "uint16" },
    ],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "getSettleDepositTotal",
    stateMutability: "view",
    inputs: [{ name: "sport", type: "uint8" }],
    outputs: [{ type: "uint256" }],
  },
] as const;

export const playscriptKernelWriteAbi = [
  {
    type: "function",
    name: "setVault",
    stateMutability: "nonpayable",
    inputs: [{ name: "vault_", type: "address" }],
    outputs: [],
  },
  {
    type: "function",
    name: "registerMatch",
    stateMutability: "nonpayable",
    inputs: [
      { name: "sport", type: "uint8" },
      { name: "kickoff", type: "uint64" },
      { name: "finalizeDelaySec", type: "uint32" },
      { name: "url", type: "string" },
      { name: "scoreboardUrl", type: "string" },
      { name: "summaryUrl", type: "string" },
      { name: "selHomeScore", type: "string" },
      { name: "selAwayScore", type: "string" },
      { name: "selHtHome", type: "string" },
      { name: "selHtAway", type: "string" },
      { name: "selYellowHome", type: "string" },
      { name: "selYellowAway", type: "string" },
      { name: "selRedHome", type: "string" },
      { name: "selRedAway", type: "string" },
      { name: "selHomeQ1", type: "string" },
      { name: "selHomeQ2", type: "string" },
      { name: "selAwayQ1", type: "string" },
      { name: "selAwayQ2", type: "string" },
      { name: "legKinds", type: "uint8[12]" },
      { name: "legWeights", type: "uint8[12]" },
    ],
    outputs: [{ type: "uint256", name: "matchId" }],
  },
] as const;
